relative_permalinks: false

url: http://jaycuthrell.com
title: Jay Cuthrell's Home Page
description: Jay Cuthrell's Home Page

google_analytics_id: UA-305670-10

source: 
root: /
permalink: /

markdown: redcarpet
date_format: "ordinal"

author :
  name : Jay Cuthrell
  email : jay@cuthrell.com
  github : jaycuthrell
  twitter : jaycuthrell
