url: https://jaycuthrell.com
title: Jay Cuthrell's Home Page
description: Perpetually Under Construction
logo:
search: false
locale: en_US

google_analytics_id:

source:
root: /
permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
date_format: "ordinal"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-feed
  - jemoji

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true


owner:
  avatar: 7years.jpg
  name : Jay Cuthrell
  email : jay@cuthrell.com
  github : jaycuthrell
  twitter :
  linkedin: jaycuthrell
  google:
    analytics:
    ad-client:
    ad-slot:


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt: Yet another imported post from Jay Cuthrell
      keywords: Jay Cuthrell
      twitter:
        card: summary
        site: https://jaycuthrell.com
        title: Read more...
        description: Words by Jay Cuthrell
        image: 400x150.png
      image:
        feature: 1year.jpg
        credit: Jay Cuthrell
  -
    scope:
      path: ""
      type: "pages"
    values:
      excerpt: Another page from Jay Cuthrell
      keywords: Jay Cuthrell
      twitter:
        card: summary
        site: https://jaycuthrell.com
        title: Read more...
        description: Words by Jay Cuthrell
        image: 400x150.png
      image:
        feature: 1year.jpg
        credit: Jay Cuthrell
