url: http://jaycuthrell.com
title: Jay Cuthrell's Home Page
description: Perpetually Under Construction
logo: 
search: false 
locale: en_US

google_analytics_id: UA-305670-10

source: 
root: /
permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
date_format: "ordinal"
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-feed
  - jemoji

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true


owner:
  avatar: bio-photo.jpg
  name : Jay Cuthrell
  email : jay@cuthrell.com
  github : jaycuthrell
  twitter : jaycuthrell
  linkedin: jaycuthrell
  google:
    analytics: UA-305670-10
    ad-client: ca-pub-4341041390314512
    ad-slot: 7619387585


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      twitter: jaycuthrell
        card: summary
        site: http://jaycuthrell.com
        title: Read more...
        description: Words by Jay Cuthrell
        image: 600x200.png
      image:
        feature: 600x200.png
        credit: Josh Atwell
        creditlink: https://twitter.com/josh_atwell/
  -
    scope:
      path: ""
      type: "pages"
    values:
      twitter: jaycuthrell
        card: summary
        site: http://jaycuthrell.com
        title: Read more...
        description: Words by Jay Cuthrell
        image: 600x200.png
      image:
        feature: 600x200.png
        credit: Josh Atwell
        creditlink: https://twitter.com/josh_atwell/
